springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'redis测试界面'
      paths-to-match: '/**'
      packages-to-scan: com.zoe.redisdemo.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8091
spring:
  data:
    redis:
      host: 10.0.7.2
      port: 6379
      password: 123123
      # redis哨兵配置
      sentinel:
        # 主节点名称
        master: mymaster
        nodes:
          - 10.0.7.2:26380
          - 10.0.7.2:26381
          - 10.0.7.2:26382
  #    # 集群的部署方式
  #    cluster:
  #      nodes:
  #        - 192.168.158.100:6380
  #        - 192.168.158.100:6381
  #        - 192.168.158.100:6382
  #      # #最大重定向次数（由于集群中数据存储在多个节点,所以在访问数据时需要通过转发进行数据定位）
  #      max-redirects: 2
  #    lettuce:
  #      pool:
  #        max-idle: 10   # 连接池中的最大空闲连接
  #        max-wait: 500   # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
  #        min-idle: 0   # 连接池中的最小空闲连接

logging:
#  pattern:
#    console: '%date{yyyy-MM-dd HH:mm:ss.SSS} | %highlight(%5level) [%green(%16.16thread)] %clr(%-50.50logger{49}){cyan} %4line -| %highlight(%msg%n)'
  level:
    root: info
    io.lettuce.core: debug
    org.springframework.data.redis: debug
