version: '3.2'
services:
  redis-6379:
    image: redis:$REDIS_VERSION
    container_name: redis6379
    volumes:
      - ./data:/data
      - ./redis6379.conf:/etc/redis/redis.conf
      - ./logs/redis6379:/var/log
    ports:
      - "6379:6379"
    command:
      redis-server /etc/redis/redis.conf
    restart: always
  redis-6380:
    image: redis:$REDIS_VERSION
    container_name: redis6380
    volumes:
      - ./data:/data
      - ./redis6380.conf:/etc/redis/redis.conf
      - ./logs/redis6380:/var/log
    ports:
      - "6380:6380"
    command:
      redis-server /etc/redis/redis.conf
    restart: always
  redis-sentinel-26380:
    image: redis:$REDIS_VERSION
    container_name: redis-sentinel-26380
    volumes:
      - ./data:/data
      - ./sentinel-cp.conf:/etc/redis/sentinel-cp.conf
      - ./logs/sentinel26380:/var/log
    ports:
      - "26380:26379"
    command:
      redis-server /etc/redis/sentinel-cp.conf --sentinel
    restart: always
  redis-sentinel-26381:
    image: redis:$REDIS_VERSION
    container_name: redis-sentinel-26381
    volumes:
      - ./data:/data
      - ./sentinel-cp.conf:/etc/redis/sentinel-cp.conf
      - ./logs/sentinel26381:/var/log/
    ports:
      - "26381:26379"
    command:
      redis-server /etc/redis/sentinel-cp.conf --sentinel
    restart: always
  redis-sentinel-26382:
    image: redis:$REDIS_VERSION
    container_name: redis-sentinel-26382
    volumes:
      - ./data:/data
      - ./sentinel-cp.conf:/etc/redis/sentinel-cp.conf
      - ./logs/sentinel26382:/var/log
    ports:
      - "26382:26379"
    command:
      redis-server /etc/redis/sentinel-cp.conf --sentinel
    restart: always
